# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/grass_mdi_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_grass_mdi(object):
    def setupUi(self, grass_mdi):
        grass_mdi.setObjectName("grass_mdi")
        grass_mdi.resize(236, 179)
        self.verticalLayout = QtWidgets.QVBoxLayout(grass_mdi)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(grass_mdi)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mdi_view = QtWidgets.QComboBox(self.frame)
        self.mdi_view.setObjectName("mdi_view")
        self.mdi_view.addItem("")
        self.mdi_view.addItem("")
        self.mdi_view.addItem("")
        self.mdi_view.addItem("")
        self.horizontalLayout.addWidget(self.mdi_view)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.run_geomorphon = QtWidgets.QToolButton(self.frame)
        self.run_geomorphon.setMaximumSize(QtCore.QSize(35, 35))
        self.run_geomorphon.setText("")
        self.run_geomorphon.setObjectName("run_geomorphon")
        self.horizontalLayout.addWidget(self.run_geomorphon)
        self.run_paramscale = QtWidgets.QToolButton(self.frame)
        self.run_paramscale.setMaximumSize(QtCore.QSize(35, 35))
        self.run_paramscale.setText("")
        self.run_paramscale.setObjectName("run_paramscale")
        self.horizontalLayout.addWidget(self.run_paramscale)
        self.run_grm_lsi = QtWidgets.QToolButton(self.frame)
        self.run_grm_lsi.setMaximumSize(QtCore.QSize(35, 35))
        self.run_grm_lsi.setText("")
        self.run_grm_lsi.setObjectName("run_grm_lsi")
        self.horizontalLayout.addWidget(self.run_grm_lsi)
        self.verticalLayout.addWidget(self.frame)
        self.grassTools = QtWidgets.QMdiArea(grass_mdi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grassTools.sizePolicy().hasHeightForWidth())
        self.grassTools.setSizePolicy(sizePolicy)
        self.grassTools.setMinimumSize(QtCore.QSize(0, 0))
        self.grassTools.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grassTools.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.grassTools.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.grassTools.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.grassTools.setActivationOrder(QtWidgets.QMdiArea.StackingOrder)
        self.grassTools.setTabsMovable(True)
        self.grassTools.setObjectName("grassTools")
        self.verticalLayout.addWidget(self.grassTools)

        self.retranslateUi(grass_mdi)
        QtCore.QMetaObject.connectSlotsByName(grass_mdi)

    def retranslateUi(self, grass_mdi):
        _translate = QtCore.QCoreApplication.translate
        grass_mdi.setWindowTitle(_translate("grass_mdi", "Form"))
        self.mdi_view.setItemText(0, _translate("grass_mdi", "Tiled"))
        self.mdi_view.setItemText(1, _translate("grass_mdi", "Cascade"))
        self.mdi_view.setItemText(2, _translate("grass_mdi", "Minimize"))
        self.mdi_view.setItemText(3, _translate("grass_mdi", "Close"))
import resources_rc
